version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: cli-table
    versions:
    - 0.3.4
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: "@types/mustache"
    versions:
    - 4.1.1
